### ISSUE TITLE
Logging Improvements

### ISSUE THREAD

**Issue by ellistarn** [aws/aws-application-networking-k8s#126]
### Log Clarity and Spam
This is the first thing we should address. Right now, it's challenging for an unfamiliar operator to understand the logs. Broadly, there's too much being emitted and too many raw objects exposed. Combing through the logs requires ignoring the vast majority of data that's written to the log.

Take for example the random snippit
```
I0312 22:30:13.317466   73652 rule_manager.go:348] findMatchingRule, rule prefix /ver1 does not match rule value /ver2
I0312 22:30:13.317481   73652 rule_manager.go:172] Rule-Create: need to BatchUpdate priority
I0312 22:30:13.317488   73652 rule_manager.go:175] Rule--Create, found existing matching rule &{{0xc000ca1340 AWS::VPCServiceNetwork::Rule rule-2} {volepond-6-wqmveaex5q default 80 HTTP HTTPRouteMatch /ver2 rule-2 {[0xc000eb8480]} 2023-03-12 22:30:11.105277 -0700 PDT m=+3037.917560676} <nil>} rulsStatus {arn:aws:vpc-lattice:us-west-2:767520670908:service/svc-040db2d76ea402e95/listener/listener-040c6949803c3a581/rule/rule-063f85bccb787bc45 rule-063f85bccb787bc45 1   true false}
I0312 22:30:13.317544   73652 rule_synthesizer.go:112] getSDKRules service: [0xc00075e580] err: <nil>
I0312 22:30:13.317550   73652 rule_synthesizer.go:116] getSDKRules, listener: [0xc0003799a0] err: <nil>
```

As an operator, there are a number of things that jump out:
* These are all INFO level logs -- do I need to know this?
* Why are there err: <nil> being printed? I don't need to know about errors unless they happen
* What is SDKRules and why do I need to be aware of this? 
* Why are naked pointers exposed `0xc0003799a0`
* Why are out of context variables exposed `true false`
* How does this relate to the lattice controller? Do I need to know about this? `BatchUpdate priority`

It's worth spending some time being thoughtful about the relationship between controller and operator, and making sure the story being told is comprehensible without knowing every line of code -- it's best if you assume zero implementation knowledge.

### Formatting 

Some objects are posted in expanded form 
```
I0312 23:11:43.320527   73652 target_group_manager.go:229] tagsOutput {
  Tags: {
    K8SServiceName: "servantshimmer-5-el6wlgodww",
    K8SHTTPRouteNamespace: "default",
    K8SParentRefTypeKey: "K8SHTTPRouteType",
    K8SServiceNamespace: "default",
    K8SHTTPRouteName: "serpentdenim-6-w6nlgev7hb"
  }
},  err: <nil>
``` 
while others are inlined 
```
I0312 23:11:43.396685   73652 cloud.go:38] Response: VpcLattice/GetTargetGroup, Body: {  Arn: "arn:aws:vpc-lattice:us-west-2:767520670908:targetgroup/tg-06ced3424d83822b1",  Config: {    HealthCheck: {      Enabled: true,      HealthCheckIntervalSeconds: 30,      HealthCheckTimeoutSeconds: 5,      HealthyThresholdCount: 5,      Matcher: {        HttpCode: "200"      },      Path: "/",      Protocol: "HTTP",      UnhealthyThresholdCount: 2    },    Port: 8090,    Protocol: "HTTP",    ProtocolVersion: "HTTP1",    VpcIdentifier: "vpc-0281c2e6397718daa"  },  CreatedAt: 2023-03-13 06:10:39.079 +0000 UTC,  Id: "tg-06ced3424d83822b1",  LastUpdatedAt: 2023-03-13 06:10:39.079 +0000 UTC,  Name: "k8s-choppervolcano-3-veb-default",  ServiceArns: [],  Status: "ACTIVE",  Type: "IP"}
```
The expanded objects add a lot of bloat, reducing readability

### Loggers and Log Levels
Right now, it's hard for an operators to differentiate between log types of ERROR, INFO, DEBUG. I love this blog from Dave Chaney that breaks down logging practices in golang: https://dave.cheney.net/2015/11/05/lets-talk-about-logging. I'm a huge fan of the implementation https://github.com/uber-go/zap, that takes these principles to heart

### TODOs

This makes me worry that something was forgotten to be implemented: `TODO HTTPRoute Delete`. 

###  Spelling
Worth auditing spelling: `Gatway` `synthesie` `Synthesise`, `ingnore` and many more

### Grammar
Worth auditing log lines and make sure they're telling a clear story to operators

It's possible to construct log lines that flow in a human readable way. 

Each context of the code constructs a log snippit, and they're concatenated using golang's %w wrap directive
```
fmt.Errorf("while doing something, %w", err)
```
e.g.,
```
"reconciling httproute, getting lattice service, 'abcdefg' not found"
```

**Comment by mikhail-aws** [comment]
Thank you Ellis for putting all together. I would prefer zap. Working on this issue now.

**Comment by xWink** [comment]
Hello, thank you for cutting this ticket and describing the troubles faced when reading logs. The above 5 PRs address all the mentioned issues, as well as some others. Info logs should be much easier to follow along now, and debug logs are also substantially cleaner and more consistent.

Please let us know if you have any more concerns!
