### ISSUE TITLE
allow K8S user to specify whether to enable access log 

### ISSUE THREAD

**Issue by liwenwu-amazon** [aws/aws-application-networking-k8s#200]
Today, K8S lattice controller does `NOT` enable access log.  This needs to be enhanced to allow K8S user to specify their intend

**Comment by bmihaescu** [comment]
@liwenwu-amazon  will you consider adding support for logs prefix as well in release v0.0.18?
The same as we do with ALB ingress: 

`alb.ingress.kubernetes.io/load-balancer-attributes: access_logs.s3.enabled=true,access_logs.s3.bucket={{.Values.bucketName}},access_logs.s3.prefix={{.Values.prefix}},idle_timeout.timeout_seconds=30,routing.http.drop_invalid_header_fields.enabled=true`
