### ISSUE TITLE
Produce error if parentRef sectionName defined in HTTPRoute is not found in Gateway

### ISSUE THREAD

**Issue by rmullinnix461332** [aws/aws-application-networking-k8s#238]
If the sectionName of the parentRefs block does not have an associated entry in the Gateway listeners section, the code creates a default listener on port 0.  This fails when it attempts to create the listener:
  
       1 listener_manager.go:90] ############resp creating listner ###########
       1 listener_manager.go:91] create listener err :InvalidParameter: 1 validation error(s) found.
- minimum field value of 1, CreateListenerInput.Port.

In model_build_listener.go, if a match of the section.Name to *parentRef.SectionName is not found, an error should be produced and returned so there is no attempt to create a default listener on port 0

**Comment by solmonk** [comment]
This does look like a bug for me. Will investigate and post the updates here. Thanks!
