### ISSUE TITLE
Targets are built for all ports of service instead of just port specified in backendRefs

### ISSUE THREAD

**Issue by rmullinnix461332** [aws/aws-application-networking-k8s#241]
We are setting up hashicorp vault as a service in lattice network.  The HTTPRoute document has a backendRefs with port 8200.  Targets are created for all ports of the service - 8200, 8201, 9091, and 9102.  Accessing the service through the lattice results in failures except for when routed to port 8200.  Expected behavior is that targets are only created for the port specified in the backend ref.

For a workaround, we created another service that just exposes port 8200 and routes to port 8200 on the vault service.

### Issue
Service
vault                   ClusterIP   XXX.XX.XX.XXX   <none>        8200/TCP,8201/TCP,9091/TCP,9102/TCP

      rules:
      - backendRefs:
        - name: vault
          kind: Service
          namespace: secrets-system
          port: 8200

Results in registered targets for each cluster member for each port
Registered Targets
  XXX.XX.XX.XXX.    8200    
  XXX.XX.XX.XXX.    8201    
  XXX.XX.XX.XXX.    9091    
  XXX.XX.XX.XXX.    9102    

Expected Result
Registered Targets
  XXX.XX.XX.XXX.    8200 

### Workaround
vault-headless          ClusterIP   XXX.XX.XX.XX    <none>        8200/TCP

**Comment by solmonk** [comment]
Thanks for bringing this to attention. We currently do create targets for every address/port combination of the service endpoint, which will result in splitting traffic across all ports in a multi-port service. We will discuss the best path forward on this issue, and keep you posted here.

**Comment by liwenwu-amazon** [comment]
@rmullinnix461332 is it possible you can show the 
```
kubectl get svc value -n secrets-system -o yaml
```

**Comment by rmullinnix461332** [comment]
`apiVersion: v1
kind: Service
metadata:
  annotations:
    banzaicloud.com/last-applied: XXX
  creationTimestamp: "2023-05-10T19:05:25Z"
  finalizers:
  - service.ki8s.aws/resources
  labels:
    app.kubernetes.io/name: vault
    global_service: "true"
    vault_cr: vault
  name: vault
  namespace: secrets-system
  ownerReferences:
  - apiVersion: vault.banzaicloud.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Vault
    name: vault
    uid: 3d3a6ef6-4394-428d-a83d-75320104043e
  resourceVersion: "95123970"
  uid: bfa0ce3e-fde5-4807-a1e7-596ad4c75bb5
spec:
  clusterIP: XXX.XX.XX.XXX
  clusterIPs:
  - XXX.XX.XX.XXX
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: api-port
    port: 8200
    protocol: TCP
    targetPort: 8200
  - name: cluster-port
    port: 8201
    protocol: TCP
    targetPort: 8201
  - name: metrics
    port: 9091
    protocol: TCP
    targetPort: 9091
  - name: statsd
    port: 9102
    protocol: TCP
    targetPort: 9102
  selector:
    app.kubernetes.io/name: vault
    vault_cr: vault
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}`

**Comment by rmullinnix461332** [comment]
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    banzaicloud.com/last-applied: XXX
  creationTimestamp: "2023-05-10T19:05:25Z"
  finalizers:
  - service.ki8s.aws/resources
  labels:
    app.kubernetes.io/name: vault
    global_service: "true"
    vault_cr: vault
  name: vault
  namespace: secrets-system
  ownerReferences:
  - apiVersion: vault.banzaicloud.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Vault
    name: vault
    uid: 3d3a6ef6-4394-428d-a83d-75320104043e
  resourceVersion: "95123970"
  uid: bfa0ce3e-fde5-4807-a1e7-596ad4c75bb5
spec:
  clusterIP: XXX.XX.XX.XXX
  clusterIPs:
  - XXX.XX.XX.XXX
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: api-port
    port: 8200
    protocol: TCP
    targetPort: 8200
  - name: cluster-port
    port: 8201
    protocol: TCP
    targetPort: 8201
  - name: metrics
    port: 9091
    protocol: TCP
    targetPort: 9091
  - name: statsd
    port: 9102
    protocol: TCP
    targetPort: 9102
  selector:
    app.kubernetes.io/name: vault
    vault_cr: vault
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

**Comment by solmonk** [comment]
Should be filtering on the correct port now.
