### ISSUE TITLE
bug: in multi-cluster setup, gateway api controller deleting each other service network

### ISSUE THREAD

**Issue by zhuoyang** [aws/aws-application-networking-k8s#252]
I am trying to use vpc lattice in multiple EKS cluster, the problem I've faced is when I use **same gateway name** the two controller will contest and try to delete off the target group and deregister the target in the target group. 
When I set **different gateway name** for each cluster, the gateway api controller tries to delete the other service network instead.

Here's the logs:
Cluster 1 (lattice-gateway) [logs](https://gist.githubusercontent.com/zhuoyang/bd18524bd64d8e9beb4fc8b570bfb82e/raw/2911084733e9d0945ef236a2b2c9e59ec5eb7899/lattice-gateway.log)
Cluster 2 (lattice-gateway-3) [logs](https://gist.githubusercontent.com/zhuoyang/bd18524bd64d8e9beb4fc8b570bfb82e/raw/2911084733e9d0945ef236a2b2c9e59ec5eb7899/lattice-gateway-3.log)

**Comment by liwenwu-amazon** [comment]
Today, we recommend to follow [config cluster design pattern](https://github.com/aws/aws-application-networking-k8s/blob/main/docs/multi-sn.md).

Today, if two EKS clusters have  same HTTPRoute and each have 2 different configs,  they will overwrite each other.  
for example

In EKS1 cluster,  HTTPRoute (foo/default) have only `path /ver1`. --> backendRef: service foo1. 
In EKS2 cluster, HTTPRoute (foo/default) have only  `path /ver2` --> backendRef: service foo2

The EKS1's lattice controller and EKS2's lattice controller will overwrite each other lattice config.

**Comment by zhuoyang** [comment]
The docs is very helpful, thanks! It should be included in the website also.

However the problem I've faced is I have two different gateway in two different cluster and the lattice controller is trying to delete the other service network

In `lattice-gateway-3` logs linked in the original post
there's an attempt to delete `lattice-gateway` service network
```
I0519 09:24:31.389877       1 service_network_manager.go:151] Created service_network(lattice-gateway-3) without vpc association
I0519 09:24:31.455791       1 service_network_synthesizer.go:156] Synthesizing Gateway: Delete stale sdkServiceNetwork lattice-gateway
I0519 09:24:31.618745       1 target_group_synthesizer.go:287] Append stale SDK TG to stale list Name k8s-staging-apigw-loadte-staging, ARN tg-047715a15a85da728
I0519 09:24:31.618789       1 target_group_synthesizer.go:287] Append stale SDK TG to stale list Name k8s-staging-ctohapi-default, ARN tg-0a26df600c05a80da
I0519 09:24:31.704868       1 service_network_manager.go:235] DeleteServiceNetworkWithContext: service_network lattice-gateway
I0519 09:24:31.876376       1 target_group_synthesizer.go:306] SynthesizeSDKTargetGroups, deleting stale target group LATTICE_RETRY 
E0519 09:24:31.900534       1 request.go:539] Failed request: VpcLattice/DeleteServiceNetwork, Payload: {  ServiceNetworkIdentifier: "sn-09ac5521622fba941"}, Error: ConflictException: ServiceNetwork sn-09ac5521622fba941 has service(s) associated
{
  RespMetadata: {
    StatusCode: 409,
    RequestID: "82cf03dd-878e-4af6-b77f-977f631139d2"
  },
  Message_: "ServiceNetwork sn-09ac5521622fba941 has service(s) associated",
  ResourceId: "sn-09ac5521622fba941",
  ResourceType: "SERVICE_NETWORK"
}
I0519 09:24:31.900552       1 service_network_manager.go:237] DeleteServiceNetworkWithContext: service_network lattice-gateway , resp {

}, err ConflictException: ServiceNetwork sn-09ac5521622fba941 has service(s) associated
{
  RespMetadata: {
    StatusCode: 409,
    RequestID: "82cf03dd-878e-4af6-b77f-977f631139d2"
  },
>>>>>> Retrying Reconcile after 20 seconds ...
  Message_: "ServiceNetwork sn-09ac5521622fba941 has service(s) associated",
  ResourceId: "sn-09ac5521622fba941",
  ResourceType: "SERVICE_NETWORK"
} 
```

**Comment by liwenwu-amazon** [comment]
Today,  lattice controller add VPC tag to each service network it created and it only can delete service network if the tag is the VPC where lattice controller runs. 

Are your 2 cluster(s) sharing same VPC?

**Comment by liwenwu-amazon** [comment]
BTW, VPC Lattice is designed to solve inter-VPC traffic. Is there any reason the 2 cluster(s) must sharing the same VPC? 

Also, each VPC is only allow to associate to a "single" lattice service network.   If you have 2 cluster(s) and want to associate to 2 different  lattice service network, you need to put them into 2 different VPC(s)

**Comment by zhuoyang** [comment]
It's just how the EKS clusters are set up currently, one of the reason that I am exploring VPC Lattice is the MCS API support.

I tried to use the same service network in both cluster (same gateway name) at first but lattice controller ends up deleting the other cluster's service/target group/target thus I am following the docs and try to use different gateway name instead. I will try out the config cluster design you linked earlier. 

> Also, each VPC is only allow to associate to a "single" lattice service network. If you have 2 cluster(s) and want to associate to 2 different lattice service network, you need to put them into 2 different VPC(s)

It seems like Lattice has a lot of assumption/restriction, is this documented anywhere?

**Comment by zhuoyang** [comment]
Is having multi cluster on single vpc, single service network not a supported use case ? I've been trying out to use the same gateway name in two different cluster, and only service export on both cluster, it seems like the target group will get overwritten

**Comment by liwenwu-amazon** [comment]
multi cluster on single VPC with single service network is supported.   The issue you ran into might be 2 cluster are using `same` k8s service name and namespace.  

In normal mode (default), a K8S service/serviceexport  is mapped to a lattice target group with. k8s-(name)-(namespace). If you using [TARGET_GROUP_NAME_LEN_MODE="long"](https://github.com/aws/aws-application-networking-k8s/blob/main/docs/enviroment.md), it is mapped to a lattice target with k8s-(name)-(namespace)-(k8s-route-name)-(vpc-id).

Can you try to give a unique name to k8s service between 2 cluster(s)?  We do have #36 to track this .

**Comment by zhuoyang** [comment]
Sorry for the late reply, I've double checked, the k8s service name is not the same, only the namespace is the same. But I am still getting the problem where one controller overwrote the other cluster's serviceexport.

Another question, does the controller support running the control cluster in another aws account?

**Comment by liwenwu-amazon** [comment]
Can you try to use different VPC for different cluster?

**Comment by liwenwu-amazon** [comment]
Yes. lattice controller should support multi cluster in a single VPC. We are working on the priority and timeline for it.  Thanks

**Comment by graehren** [comment]
We created a [feature request ticket](https://github.com/aws/aws-application-networking-k8s/issues/388) where we will track development for this.

**Comment by solmonk** [comment]
With the latest change, service networks will no longer be managed by the controller. For this use case you can create service networks outside the controller and refer to it from multiple gateways (over multiple clusters) . Note that service network-VPC association is still manageable by the controller using VPCAssociationPolicy.
