### ISSUE TITLE
Q: utilizing VPC lattice for multiple kubernetes cluster in a DR scenario?

### ISSUE THREAD

**Issue by zhuoyang** [aws/aws-application-networking-k8s#253]
Currently I am exploring the feasibility of utilizing VPC Lattice to support a multi-cluster setup for DR scenario, ideally we would have a similar set of kubernetes resources deployed in two different EKS cluster, then control the weightage and routing at VPC Lattice service. 
Aside from issue mentioned in #252, it doesn't seems to be possible in current gateway API controller state, since we will need to use the MCS api (ServiceImport and ServiceExport) in order to configure the service to route to different target group. Is there a way that I can create same HTTPRoute on both cluster while maintaining only one service in VPC lattice? or is there any other recommendation where we can utilize VPC Lattice to handle DR scenario, eg. in case of one EKS cluster is completely down, we can move all the application to another cluster while maintaining the same vpc lattice/domain name? 

![image](https://github.com/aws/aws-application-networking-k8s/assets/1240039/2c731e6d-e30a-45a6-9c2c-ff67a8a0946b)

**Comment by liwenwu-amazon** [comment]
Yes.   By default,  a HTTPRoute in eks1 and eks2 cluster have `same` name and namespace, it will be mapped to a `single` lattice service.

We recommended a  architecture where you have a [config cluster](https://github.com/aws/aws-application-networking-k8s/blob/main/docs/multi-sn.md) to define HTTPRoute.  And data cluster just use the service

**Comment by jansvive** [comment]
Dear Requester, Hope we clarified the issue. In case you have anymore questions please do not hesitate to reach out.
