### ISSUE TITLE
Service unavailable

### ISSUE THREAD

**Issue by iluwatar** [aws/aws-application-networking-k8s#254]
Hi,

I followed the deployment steps at https://www.gateway-api-controller.eks.aws.dev/deploy/

Next, I tried to set up the single cluster/VPC service-to-service communications as indicated here: https://www.gateway-api-controller.eks.aws.dev/getstarted/

My problem appears in step "check service connectivity". When I exec into the pods and try to call the service using the curl command, e.g. curl -v inventory-aws-application-ne-03449e711929f70b4.7d67968.vpc-lattice-svcs.eu-west-1.on.aws, it always responds with 503 service not available.

Any ideas how to debug what is going wrong?

**Comment by liwenwu-amazon** [comment]
You may want to double check if security group is configured correctly.  Can you check the flowlog and see if anything is dropped due to security group?

**Comment by iluwatar** [comment]
Recreated the cluster from scratch and got it working. Thanks for help!

**Comment by laserpedro** [comment]
Hello, why has this issue been closed ? having the VPC CNI plugin installed is IMO pretty basic when operating an EKS cluster so it can be a blocker to use the controller at all actually ...
