### ISSUE TITLE
For serviceexport, targets are built for all ports of instead of just port specified in the serviceimport of backendRefs

### ISSUE THREAD

**Issue by liwenwu-amazon** [aws/aws-application-networking-k8s#267]
This is similar to #241 . The same issue happens for serviceexport too.

**Comment by liwenwu-amazon** [comment]
workaround:  create a separate K8S service which only contains the ports need to used and create a separate service export object to reference this K8S service

**Comment by jansvive** [comment]
Thanks for the feature request! We will be adding this to our intake for prioritization, but we also try to take in popular feature requests based on :+1::skin-tone-4: from the community.
