### ISSUE TITLE
ServiceExport deletion leaks targetgroup if the corresponding K8sService have already been deleted

### ISSUE THREAD

**Issue by zijun726911** [aws/aws-application-networking-k8s#269]
ServiceExport deletion leaks targetgroup if the corresponding K8sService have already been deleted.

More details on how to reproduce this bug (could 100% reproduce it):

### For the ServiceExport, it could have 2 scenarios:

- Scenario1, all good no bug: 
    -  Given: create one k8sService, and one its corresponding ServiceExport, create ServiceExport could trigger controller to create a target group success
    -  __Now the k8sService still exists__,  if I do `kubectl delete serviceexport myserviceexport` , could trigger target group deletion correctly

- Scenario2, has bug,  target group leaking
    -  Given: create 1 k8sService, and 1 its corresponding ServiceExport, create ServiceExport could trigger controller to create a target group success
    -  do `kubectl delete service myservice`
    -  __Now the k8sService does not exist__, if I do `kubectl delete serviceexport myserviceexport`,  target group deletion will not be triggered, which cause target group leaking

**Comment by liwenwu-amazon** [comment]
We should use service finalizer to prevent K8S service being deleted,  if this service is referenced by HTTPRoute or ServiceExport

**Comment by zijun726911** [comment]
> We should use service finalizer to prevent K8S service being deleted, if this service is referenced by HTTPRoute or ServiceExport
Can not quite get what the benefit of it? That can also increase the chance the user is blocked to delete K8S services?

**Comment by solmonk** [comment]
Why would we interrupt k8s service lifecycle though? We already have a behavior of deregistering all targets when service is deleted. HTTPRoute will have a rule that points to empty upstream but it is fine because that's actually the way the user configured k8s config. We should update HTTPRoute resolvedRef status to false instead.

I believe we should move away of user experience of waiting forever. Finalizers are hooks that handle necessary cleanup process, and should not be used for blocking users.

**Comment by liwenwu-amazon** [comment]
This is very similar to the logic that lattice had on target group and service that you are not allowed to delete rules or services if it references some target group.

Allow deleting K8S service while it is referenced by other objects (e.g. serviceexport, httproute) make those object handling logic more complicated and error prone.

**Comment by liwenwu-amazon** [comment]
for "user experience of waiting forever.", i believe it is only come from kubectl command `kubectl delete xxxx`.  If you want a error msg (similar to lattice CLI), you need to add webhook for our controller.

**Comment by solmonk** [comment]
I agree, and webhooks seem like a much better solution than finalizers.

**Comment by zijun726911** [comment]
Partially fixed by: https://github.com/aws/aws-application-networking-k8s/pull/389

The rest part of (ServiceExport's ServiceImport refered by Route) bug fix  need the targetGroup datastore refactoring
