### ISSUE TITLE
Gateway reconciler retries immediately instead of sleeping for 20 sec then retry, when the gateway haven’t yet changed to its desired state 

### ISSUE THREAD

**Issue by zijun726911** [aws/aws-application-networking-k8s#270]
Gateway reconciler retries immediately instead of sleeping for 20 sec then retry, when the gateway haven’t yet changed to its desired state(i.e. if code return errors.New(LATTICE_RETRY) in the middle of reconciliation process ) 

My observation is this could be a regression issue, We didn't have this problem before until release v0.0.11?

**Comment by solmonk** [comment]
Not experiencing this after #287, should not fall into loop after the timestamp change.
