### ISSUE TITLE
Add more Httproute related e2etest

### ISSUE THREAD

**Issue by zijun726911** [aws/aws-application-networking-k8s#273]
Some test cases that we could prioritize to automate in the e2etest code :

Test case1: HTTPRoute, serviceimport, service miscellaneous Creation order1 
    1. create serviceimport1
    2. create HTTPRoute (with backendref1 serviceexport1)
    3. create serviceexport1
    4. create service1 (all lattice resource will be created at this moment)

Test case2: HTTPRoute, serviceimport, service miscellaneous Creation order2
    1. create HTTPRoute  (with backendref serviceexport1)
    2. create serviceimport1
    3. create service1
    4. create serviceexport1 (all lattice resource will be created at this moment)

Test case3: HTTPRoute, serviceimport, service miscellaneous Creation order3 
    1. create serviceexport  (with backendref serviceexport1)
    2. create httproute1
    3. create serviceimport1
    4. create service1 (all lattice resource will be created at this moment)
    
Test case4: httproute update test 1
      Done in #268 : https://github.com/aws/aws-application-networking-k8s/blob/306fe5d78dab179e4467ed62c784e45e0efaf1b0/test/suites/integration/httproute_mutation_do_not_leak_target_group_test.go

Test case5: httproute update test 2
    1. kubectl apply -f myapp.yaml which includes
        - Gateway
        - Service1
        - Service2
        - ServiceImport2
        - ServiceExport2
        - HTTPRoute (backendref1 service1 only)
        - Deployment1
        - Deployment2
    2. Update HTTPRoute to add another rule (backendref2 serviceImport2) , now  HTTPRoute has (backendref1 service1, backendref2 serviceImport2 )
    3. Verify LatticeService’rules are updated correctly
    4. Update HTTPRoute to only have one rule  (backendref2 serviceImport2), now  HTTPRoute has (backendref2 serviceImport2 ) one rule only
    5.  Verify LatticeService’rules are updated correctly and targetgroup1 is deleted

**Comment by jansvive** [comment]
Thanks for the feature request! We will be adding this to our intake for prioritization, but we also try to take in popular feature requests based on :+1::skin-tone-4: from the community.
