### ISSUE TITLE
HTTPRoute status update triggered indefinitely

### ISSUE THREAD

**Issue by solmonk** [aws/aws-application-networking-k8s#282]
Likely caused by #275 - HTTPRoute status update triggers another reconciliation which ends up triggering another HTTPRoute status update. The status update should happen only once as no specifications are changing.

Possible root cause is that status conditions keeps getting updated due to the timestamp value.

**Comment by jansvive** [comment]
Thanks for reporting the issue, we will be investigating it further. Please watch this channel for more updates, and feel free to reach out.
