### ISSUE TITLE
Getting started doc's multi-cluster/multi-VPC serviceimport needs additional config ?

### ISSUE THREAD

**Issue by pmcgrath** [aws/aws-application-networking-k8s#295]
I tried the the [multi cluster/multi VPC](https://github.com/aws/aws-application-networking-k8s/blob/main/docs/getstarted.md#set-up-multi-clustermulti-vpc-service-to-service-communications) from the getting started doc
- I do have different cluster names and use a namespace (Same on both clusters)
- But when I ran the curl test on step 8 I only got `Inventory-ver2 handler pod` responses

When I looked at the logs of the controller can see lots of these 
```
HandleReconcileError handle Error LATTICE_RETRY 
>>>>>> Retrying Reconcile after 20 seconds ...
```

Looking at this [file](https://github.com/aws/aws-application-networking-k8s/blob/main/examples/inventory-ver2-import.yaml#L6C37-L6C48) which is supposed to import inventory-ver2 into cluster-1
- Am I supposed to replace `"your-vpc-id"` ? 
- We should set/override the `"lattice-eks-test-2"` if using a different cluster name ?

I have tried setting both (Source and import cluster values), but have had no luck

Thanks in advance
Pat

**Comment by solmonk** [comment]
Hello, LATTICE_RETRY error is also expected to happen in normal scenarios because typically there are delays on resource registration, so it is hard to tell anything from just that error. Would you mind sharing more of your controller log to help troubleshoot?

And yes, you will need to replace the annotations.

**Comment by mikhail-aws** [comment]
closing for now, please re-open if it's still relevant
