### ISSUE TITLE
Remove out-dated comments

### ISSUE THREAD

**Issue by liwenwu-amazon** [aws/aws-application-networking-k8s#299]
We have added support to allow multiple gateway(s), but this [comment](https://github.com/aws/aws-application-networking-k8s/blob/38f2b672595c1d68254b7f750cabbde2f528f4e6/controllers/httproute_controller.go#L167C22-L167C22) still left in the code and need to be removed

**Comment by vavrajosef** [comment]
Hello, I would like to work on this issue. Please assign it to me.

**Comment by vavrajosef** [comment]
@liwenwu-amazon I have removed the comment you mentioned and another following that still assumed that there is only one parent.
Please look at my [PR](https://github.com/aws/aws-application-networking-k8s/pull/301).

There is still code that assumes there is only one parentRef - [this line for example](https://github.com/aws/aws-application-networking-k8s/blob/38f2b672595c1d68254b7f750cabbde2f528f4e6/controllers/httproute_controller.go#L169). Shouldn't there be a followup issue that removes this indexed approach (and for example loops through parentRefs)?

**Comment by jansvive** [comment]
Is this done, can we close this one

**Comment by vavrajosef** [comment]
@jansvive yes it is done, this can be closed.

**Comment by solmonk** [comment]
Closing the issue. I am revisiting overall cross namespace and multiple reference handling in general, let me create a new ticket for this after the investigation.
