### ISSUE TITLE
feature request: be able to customize target group names in k8s

### ISSUE THREAD

**Issue by shulin-sq** [aws/aws-application-networking-k8s#315]
When creating multiple target groups I noticed that their naming were cut off/not very helpful given my organization's naming scenes of services and namespaces in k8s.

As per the documentation https://github.com/aws/aws-application-networking-k8s/blob/main/docs/enviroment.md 

the current target group names is 

k8s-(k8s service name)-(k8s service namespace)

and the long version includes a vpc id which we do not need since it's the same for all of our workloads right now. 

Currently my organization names services and namespaces the same (each service gets its own namespace) so the naming of the target group becomes k8s-foo-foo. Any uniqueness comes for a suffix behind the service name, so k8s-foobar-foo. However if the service name is too long the unique suffix is cut off.

Since we have this weird naming scheme, I'm wondering how feasible it would be to introduce a new naming pattern or make that configurable. For example some ideas may be
- an env variable (or perhaps a better input location, perhaps a configmap for the controller?) where we can define a target group naming format 
- a different mode that does not cut off characters of the service name (with a longer character limit for the target group)

**Comment by solmonk** [comment]
Hi, thanks for spotting this issue. We are working on increasing the size limit of target group names in the next release.

**Comment by solmonk** [comment]
TG name size limit got increased with recent naming changes, targeting next release. For full customization capability, we need to figure out direction and details.

**Comment by erikfuller** [comment]
@shulin-sq, can you please have a read through #425 and see if the proposed approach would address your use case?

**Comment by graehren** [comment]
@shulin-sq we released EKS controller version [v0.0.18](https://github.com/aws/aws-application-networking-k8s/releases/tag/v0.0.18) yesterday which contains a revised TG naming strategy. This update should resolve your issues with the TG naming conflict. Please let us know if you have any other questions or feature requests.
