### ISSUE TITLE
[Bug] Http/GRPCRoute's backendref port didn't take effect when updating HttpRoute/GRPCRoute/k8Service

### ISSUE THREAD

**Issue by zijun726911** [aws/aws-application-networking-k8s#359]
For following scenarios, Http/GRPCRoute's backendref ports didn't take effect and the controller will create lattice targets with unexpected ports:

- Update k8Service
- Update  Http/GRPCRoute (unexpected targets ports can be created in a moment and then be de-registered immediately with draining, the reason is service_controller [`Watches` HTTPRoute and GRPCRoute](https://github.com/aws/aws-application-networking-k8s/blob/138c1126540432673cd0628ed401c07bcdf96ea2/controllers/service_controller.go#L92) and do [enqueueImpactedService()](https://github.com/aws/aws-application-networking-k8s/blob/1c36c1e706256a24cefd6af63c0d47124dc1310a/controllers/eventhandlers/route.go#L41) )

Root cause:
In this PR #351, we only assign  `&latticeTargetsModelBuildTask{ backendRefPort: port}` in `(t *latticeServiceModelBuildTask) buildTargets()`, but miss to do that in  [`(b *LatticeTargetsModelBuilder) Build()`](https://github.com/aws/aws-application-networking-k8s/blob/138c1126540432673cd0628ed401c07bcdf96ea2/pkg/gateway/model_build_targets.go#L52).

Adding ` backendRefPort: port` logic in the [`(b *LatticeTargetsModelBuilder) Build()`](https://github.com/aws/aws-application-networking-k8s/blob/138c1126540432673cd0628ed401c07bcdf96ea2/pkg/gateway/model_build_targets.go#L52)` is quite likely could fix it.

Furthermore, build targets logic could diverge triggering from k8sService/Route/ServiceExport, should we consider to refactor and combine them?

**Comment by solmonk** [comment]
For ServiceExport, instead of using backendRef ports we are relying on annotations for determining ports - because at the moment of creating TGs we may not have HTTPRoute in the same cluster. Please try setting up `"multicluster.x-k8s.io/port"` annotation on ServiceExport.

**Comment by zijun726911** [comment]
Ok, I think only happen for updating HttpRoute/GRPCRoute/Service scenarios, no  ServiceExport

**Comment by solmonk** [comment]
So your explanation is:
* k8s Service change does trigger all these - ServiceReconciler, HTTPRouteReconciler, and ServiceExportReconciler.
* ServiceReconciler is not aware of port information so tries to register all endpoints instead of watching backendRef.

I think it makes sense. Actually I don't get why ServiceReconciler even exists, the other two reconcilers are able to handle that anyways.

**Comment by solmonk** [comment]
Perhaps a better path forward is to remove ServiceReconciler and letting the other two reconcilers watch endpoint events instead.
