### ISSUE TITLE
Support multi-cluster setup within a single VPC

### ISSUE THREAD

**Issue by graehren** [aws/aws-application-networking-k8s#388]
This is a feature request to support multi-cluster setup within a single VPC.

Currently, the controller supports [multi-cluster service networks](https://github.com/aws/aws-application-networking-k8s/blob/main/docs/multi-sn.md) when the clusters are running in different VPCs, but when customers are running a multi-cluster setup in a single VPC there can be unexpected behaviour from the controller. Due to customer internal architecture and processes they are unable to move a multi-VPC setup. 

See the related ticket where customer had this issue: 
https://github.com/aws/aws-application-networking-k8s/issues/252

**Comment by mikhail-aws** [comment]
#392 #393
