### ISSUE TITLE
[Docs] Improve site structure and diagrams

### ISSUE THREAD

**Issue by graehren** [aws/aws-application-networking-k8s#403]
## Requirements

- Work with technical writer to improve the site structure and organization
- Make the docs more searchable with clear and search optimized headlines
- Improve the diagrams to improve the readability

**Comment by graehren** [comment]
Look at issue https://github.com/aws/aws-application-networking-k8s/issues/253 for example on improving docs for architecture with multiple service networks. Use https://github.com/aws/aws-application-networking-k8s/blob/main/docs/multi-sn.md as a starting point.

**Comment by zijun726911** [comment]
Done by https://github.com/aws/aws-application-networking-k8s/pull/630
