### ISSUE TITLE
Not able to set env var for target group long name via helm deploy

### ISSUE THREAD

**Issue by rmullinnix461332** [aws/aws-application-networking-k8s#408]
The helm chart only supports environment var names for aws region, aws account id and cluster vpc id.  Need the ability to also set TARGET_GROUP_NAME_LEN_MODE as part of helm deploy.  We run multiple VPCs under the same account id.  We have a separate qa environment on a separate vpc where we want to stage lattice services.  The default setup for target group names results in the same target group name for both vpcs.  The target group name in qa is overwriting the production target group.  The TARGET_GROUP_NAME_LEN_MODE resolves this issue, but not able to set this value on helm deploy.

helm/values.yaml:
77  targetGroupNameLen: short

helm/templates/deployment.yaml
85.         - name: TARGET_GROUP_NAME_LEN_MODE
86.           value: {{ .Values.targetGroupNameLen }}

or add to the existing config map

**Comment by xWink** [comment]
Thanks for reporting the issue, we will be investigating it further. Please watch this channel for more updates, and feel free to reach out!

**Comment by zijun726911** [comment]
> We run multiple VPCs under the same account id. We have a separate qa environment on a separate vpc where we want to stage lattice services. The default setup for target group names results in the same target group name for both vpcs. The target group name in qa is overwriting the production target group.

We have plan to deprecate the different TARGET_GROUP_NAME_LEN_MODE, and make normal target group name model don't cause above bug. It's already in our roadmap, we target to fix it for v0.1.0 beta release.

**Comment by erikfuller** [comment]
@rmullinnix461332 can you have a look at #425 and see if the proposed approach would address your use case?

**Comment by graehren** [comment]
Targeting to resolve this issue with our upcoming [v0.0.18 release](https://github.com/aws/aws-application-networking-k8s/milestone/3)

**Comment by graehren** [comment]
This should be resolved with PR #457 which will be available in the next release.

**Comment by graehren** [comment]
@rmullinnix461332 we released EKS controller version [v0.0.18](https://github.com/aws/aws-application-networking-k8s/releases/tag/v0.0.18) yesterday which contains a revised TG naming strategy. This update should resolve your issues with the TG naming conflict. Please let us know if you have any other questions.
