### ISSUE TITLE
Only create Lattice resources for services tagged with x

### ISSUE THREAD

**Issue by shulin-sq** [aws/aws-application-networking-k8s#427]
I'd like target group creation to be conditional on some metadata of the service object. For example, if the service has an annotation such as latticeEnabled.

The desire comes from the fact that Service objects are not specific to the gateway api and can be used for other configurations https://kubernetes.io/docs/concepts/services-networking/service/ I'd like to distinguish between which service objects should also map to lattice vs not.

Is there any issues with this idea/is it already possible?

**Comment by solmonk** [comment]
A k8s Service object does not always create Lattice TargetGroups. TGs are only created if a Service is a backendRef of existing HTTPRoute/GRPCRoute or a ServiceExport is created.

Could you clarify with actual use cases, etc?

**Comment by shulin-sq** [comment]
@solmonk thanks for the clarification, that is sufficient at this time.
