### ISSUE TITLE
Helm chart failing to install when IMDS is unavailable

### ISSUE THREAD

**Issue by solmonk** [aws/aws-application-networking-k8s#435]
For the following configuration variables, we rely on IMDS to get the right values:
* `REGION`
* `AWS_ACCOUNT_ID`
* `CLUSTER_VPC_ID`
* `CLUSTER_NAME`

In many environments, IMDS is not available. (e.g. k8s w/o EC2 instance, self-managed clusters with IMDS access blocked) In this case, the values should be provided as environment variable through Helm chart. However, on [values.yaml](https://github.com/aws/aws-application-networking-k8s/blob/main/helm/values.yaml) we have 3 of these but `CLUSTER_NAME` is missing.

This is causing any Helm chart installation to fail in IMDS-disabled environment. One case reported is kops which [disables IMDS access for pods](https://kops.sigs.k8s.io/iam_roles/#instance-iam-roles) by default.

Path to fix:
* Add cluster name to helm chart value.
* Update documentation with proper IMDS setup instruction. Setting IMDS hops to 2 or higher is worth mentioning.

Temporary mitigation:
* If you are using IMDSv2, try increasing the hop limit to 2 or higher.
* Deploy manually. Modify `deploy-v0.0.17.yaml` and add above 4 environment variables.

**Comment by graehren** [comment]
Need IMDS related section in our documentation
