### ISSUE TITLE
TargetGroupPolicy and VpcAssociationPolicy CRD status Update

### ISSUE THREAD

**Issue by zijun726911** [aws/aws-application-networking-k8s#440]
Currently controller behavior is: if multiple TargetGroupPolicies (tgp), VpcAssociationPolicies(vap) apply to the same k8s obj, only the first policy will take effect and the controller will ignore the rest of policies(will print a error log for it). If that happen, we should use a better way to represent this error by updating policy status: for example, If there are two tgps attached to one svc(serviceExport), one policy is set to `accepted` status and the other one is set to `conflicted` status.

(Other policies CRDs or even other controller managed k8s objs may also need proper status update )

**Comment by graehren** [comment]
Thanks for reporting the issue, we will be investigating it further. Please watch this channel for more updates, and feel free to reach out.

**Comment by graehren** [comment]
We released EKS controller version [v0.0.18](https://github.com/aws/aws-application-networking-k8s/releases/tag/v0.0.18) yesterday which contains a revised TG naming strategy to avoid conflicts. Target group names will no longer conflict across clusters for identical specs. Target group names now include a randomized suffix and all identification/deduplication is done through first class fields on the target group and tags.

Marking this issue as resolved. Thank you for you support.
