### ISSUE TITLE
Multiple-cluster Service Network / Gateway deletion

### ISSUE THREAD

**Issue by Tim-AWS** [aws/aws-application-networking-k8s#445]
**Summary**

It appears if I create a SN in one cluster and then create a SN of the same name in a second cluster, both without service or VPC associations that when the SN is deleted in the first cluster, the creator, it removes the SN from both the first cluster and the AWS Console but the SN remains in the second cluster although it does not exit. Additionally the SN with a VPC association, in another VPC is not removed when the gateway is deleted in the cluster which originally created it, the delete hangs.
 

**Setup**

Clusters are in separate VPC's, one cluster is IPv4, the other IPv6, I ran the tests swapping clusters i.e. cluster 1 ipv4 / cluster 2 ipv6 and again with cluster 1 ipv6 / cluster 2 ipv4. Controllers on both are v0.0.17 installed via helm. Kubernetes version are both 1.27, v1.27.3-eks-a5565ad and v1.27.4-eks-8ccc7ba.

**How to replicate**

1. Console: Create SN “staging” and associate client VPC

In the AWS Console you can see the SN "staging" with 1x VPC Association

2. Cluster 1: Create SN’s “prod” and “dev”, and add existing SN “staging” via following manifest

$ k apply -f global/gateways.yaml 
namespace/gateway created
gateway.gateway.networking.k8s.io/dev created
gateway.gateway.networking.k8s.io/prod created
gateway.gateway.networking.k8s.io/staging created
$ k get gateway -A                                                                                                  
NAMESPACE   NAME      CLASS                ADDRESS   PROGRAMMED   AGE
gateway     dev       amazon-vpc-lattice             True         42s
gateway     prod      amazon-vpc-lattice             True         42s
gateway     staging   amazon-vpc-lattice             True         42s

In the AWS Console you can see the SN "staging" with 1x VPC Association, "prod" 0x PC Association, and dev 1x VPC Association.

3. Cluster 2: add all SN’s vis the same manifest

$ k apply -f global/gateways.yaml 
namespace/gateway created
gateway.gateway.networking.k8s.io/dev created
gateway.gateway.networking.k8s.io/prod created
gateway.gateway.networking.k8s.io/staging created
$ k get gateway -A
NAMESPACE   NAME      CLASS                ADDRESS   PROGRAMMED   AGE
gateway     dev       amazon-vpc-lattice             True         37s
gateway     prod      amazon-vpc-lattice             True         37s
gateway     staging   amazon-vpc-lattice             True         36s

In the AWS Console you can see the SN "staging" with 1x VPC Association, "prod" 0x PC Association, and dev 2x VPC Associations.

Note: SN “prod” doesn’t have any service or VPC associations.

4. Cluster 1: delete the SN’s

$ k delete -f global/gateways.yaml 
namespace "gateway" deleted
gateway.gateway.networking.k8s.io "dev" deleted
gateway.gateway.networking.k8s.io "prod" deleted
gateway.gateway.networking.k8s.io "staging" deleted

[hangs - Cluster 1 controller logs]

{"level":"info","ts":1697742051.149465,"logger":"controller.gateway","caller":"controllers/gateway_controller.go:115","msg":"reconcile","name":"dev"}
{"level":"info","ts":1697742051.1517541,"logger":"controller.route","caller":"eventhandlers/gateway.go:52","msg":"Received Update event for Gateway dev-gateway"}
{"level":"info","ts":1697742051.1652253,"logger":"controller.route","caller":"eventhandlers/gateway.go:52","msg":"Received Update event for Gateway prod-gateway"}
{"level":"info","ts":1697742051.1652484,"logger":"controller.route","caller":"eventhandlers/gateway.go:52","msg":"Received Update event for Gateway prod-gateway"}
{"level":"info","ts":1697742051.1969402,"logger":"controller.route","caller":"eventhandlers/gateway.go:52","msg":"Received Update event for Gateway staging-gateway"}
{"level":"info","ts":1697742051.1970198,"logger":"controller.route","caller":"eventhandlers/gateway.go:52","msg":"Received Update event for Gateway staging-gateway"}
{"level":"info","ts":1697742051.5980747,"logger":"controller.gateway","caller":"controllers/gateway_controller.go:119","msg":"requeue request","name":"dev","requeueAfter":20}
{"level":"info","ts":1697742051.5982337,"logger":"controller.gateway","caller":"controllers/gateway_controller.go:115","msg":"reconcile","name":"prod"}
{"level":"info","ts":1697742052.085508,"logger":"controller.gateway","caller":"controllers/gateway_controller.go:123","msg":"reconciled","name":"prod"}
{"level":"info","ts":1697742052.0856056,"logger":"controller.gateway","caller":"controllers/gateway_controller.go:115","msg":"reconcile","name":"staging"}
{"level":"info","ts":1697742052.3715825,"logger":"controller.gateway","caller":"controllers/gateway_controller.go:123","msg":"reconciled","name":"staging"}
{"level":"info","ts":1697742052.371673,"logger":"controller.gateway","caller":"controllers/gateway_controller.go:115","msg":"reconcile","name":"prod"}
{"level":"info","ts":1697742052.3717017,"logger":"controller.gateway","caller":"controllers/gateway_controller.go:123","msg":"reconciled","name":"prod"}
{"level":"info","ts":1697742052.3717282,"logger":"controller.gateway","caller":"controllers/gateway_controller.go:115","msg":"reconcile","name":"staging"}
{"level":"info","ts":1697742052.371744,"logger":"controller.gateway","caller":"controllers/gateway_controller.go:123","msg":"reconciled","name":"staging"}
{"level":"info","ts":1697742071.599308,"logger":"controller.gateway","caller":"controllers/gateway_controller.go:115","msg":"reconcile","name":"dev"}
{"level":"info","ts":1697742072.1061194,"logger":"controller.gateway","caller":"controllers/gateway_controller.go:119","msg":"requeue request","name":"dev","requeueAfter":20}
{"level":"info","ts":1697742092.1067379,"logger":"controller.gateway","caller":"controllers/gateway_controller.go:115","msg":"reconcile","name":"dev"}
{"level":"info","ts":1697742092.5588582,"logger":"controller.gateway","caller":"controllers/gateway_controller.go:119","msg":"requeue request","name":"dev","requeueAfter":20}

[In another terminal, cluster 1 I can see gateway/SN dev isn’t deleted I assume as it has a VPC association and was created in this cluster]

[Cluster 1]
$ k get gateway -A
NAMESPACE   NAME   CLASS                ADDRESS   PROGRAMMED   AGE
gateway     dev    amazon-vpc-lattice             True         6m30s

In the AWS Console you can see the SN "staging" with 1x VPC Association, "prod" has been removed, and dev 1x VPC Association.

[Cluster 2]
$ k get gateway -A
NAMESPACE   NAME      CLASS                ADDRESS   PROGRAMMED   AGE
gateway     dev       amazon-vpc-lattice             True         14m
gateway     prod      amazon-vpc-lattice             True         14m
gateway     staging   amazon-vpc-lattice             True         14m

Note: prod only exists in Cluster 2

———

apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: dev
  namespace: gateway
  annotations:
    application-networking.k8s.aws/lattice-vpc-association: "true"
spec:
  gatewayClassName: amazon-vpc-lattice
  listeners:
  - name: http
    protocol: HTTP
    port: 80
  - name: https
    protocol: HTTPS
    port: 443
  - name: wildcard-demo-vpc-lattice
    protocol: HTTPS
    port: 443
    tls:
      mode: Terminate
      options:
        application-networking.k8s.aws/certificate-arn: <arn>
  
---

[Gateway manifest used in both clusters]

apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: prod
  namespace: gateway
  annotations:
    application-networking.k8s.aws/lattice-vpc-association: "false"
spec:
  gatewayClassName: amazon-vpc-lattice
  listeners:
  - name: http
    protocol: HTTP
    port: 80
  - name: https
    protocol: HTTPS
    port: 443
  - name: wildcard-demo-vpc-lattice
    protocol: HTTPS
    port: 443
    tls:
      mode: Terminate
      options:
        application-networking.k8s.aws/certificate-arn: <arn>

---

apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: staging
  namespace: gateway
  annotations:
    application-networking.k8s.aws/lattice-vpc-association: "false"
spec:
  gatewayClassName: amazon-vpc-lattice
  listeners:
  - name: http
    protocol: HTTP
    port: 80
  - name: https
    protocol: HTTPS
    port: 443
  - name: wildcard-demo-vpc-lattice
    protocol: HTTPS
    port: 443
    tls:
      mode: Terminate
      options:
        application-networking.k8s.aws/certificate-arn: <arn>

**Comment by solmonk** [comment]
This is a known issue leading to a few similar issues such as #388. Currently a work for service network ownership is going on, to address this kind of conflict. We will provide you with more details soon.

In this kind of case (multiple clusters sharing same service network, especially when VPCs are the same), I would recommend creating and managing service network outside the cluster - we are looking for it to be the default setting in the future.

**Comment by graehren** [comment]
Targeting this fix for our next release [milestone v0.0.18](https://github.com/aws/aws-application-networking-k8s/milestone/3)

**Comment by graehren** [comment]
Work in progress with PR #502. Targeting release for milestone v1

**Comment by solmonk** [comment]
Should be resolved as part of SN behavior change on v1.0.0 release.
