### ISSUE TITLE
Documentation: Ingress Security Group in deployment documentation doesn't properly use the prefix list

### ISSUE THREAD

**Issue by niax** [aws/aws-application-networking-k8s#455]
On the [deployment documentation](https://github.com/aws/aws-application-networking-k8s/blob/a2d5b973b3516f11784d1a764830e8de2eadf4a7/docs/deploy.md?plain=1#L19-L22) loads the prefix list and then just uses the first prefix. This will be a problem in the future when there's more than one prefix, or if the prefixes change.

Security Groups can reference prefix lists by ID, and dynamically update when the entries in them change:

```
$ aws ec2 authorize-security-group-ingress --group-id $SG_ID --ip-permissions "PrefixListIds=[{PrefixListId=${PREFIX_LIST_ID}}],IpProtocol=-1"
```

Should do the same as the current command, and also apply when the prefix lists change.

**Comment by graehren** [comment]
Targeting this fix for upcoming [milestone release](https://github.com/aws/aws-application-networking-k8s/milestone/4)
