### ISSUE TITLE
`iam:CreateServiceLinkedRole` not needed but included in recommended-inline-policy

### ISSUE THREAD

**Issue by jaypipes** [aws/aws-application-networking-k8s#48]
The gateway controller never calls `iam:CreateServiceLinkedRole`:

https://github.com/aws/aws-application-networking-k8s/search?q=ServiceLink

and yet `iam:CreateServiceLinkedRole` is [listed in the recommended-inline-policy.json file](https://github.com/aws/aws-application-networking-k8s/blob/04e9dc8abcda230acecabc1551629023018d5aa9/config/iam/recommended-inline-policy.json#L8).

This line should be removed from the recommended-inline-policy.json file if the controller is not actually calling that API.

**Comment by mikhail-aws** [comment]
should be ok to remove it and update documentation, should be an easy pick

**Comment by scottlaiaws** [comment]
We need this permission in case an account doesn't have a service linked role: https://docs.aws.amazon.com/vpc-lattice/latest/ug/using-service-linked-roles.html#create-slr. Perhaps, we can scope the permission down to be only able to create service linked role with name `AWSServiceRoleForVpcLattice`

**Comment by scottlaiaws** [comment]
updated docs with scoped down permission
