### ISSUE TITLE
Optimize unused target group cleanup

### ISSUE THREAD

**Issue by solmonk** [aws/aws-application-networking-k8s#552]
Unused target group cleanup is called at the end of every route reconciliation - this means if the controller is to reconcile 100 target groups, we are cleaning up target groups 100 times. Target group cleanup is a pretty heavy operation even when cleaning nothing, involving a few round trip of list/get calls. This is impacting controller throughput of creating resources, and degrading performance of controller startup.

We could either:
* make it an asynchronous process that runs every X minute.
* somehow make it not happen when there was a recent cleanup

We should also make sure to avoid race condition when taking the first approach, because current target group cleanup logic is built on the assumption that reconciliation is done. The simplest way might be just to put locks - not the best looking but will still be better than current logic in terms of performance.

**Comment by mikhail-aws** [comment]
I dont think we should do global cleanup at all, including GC. Global GC has few implications:

- Global lock - easy to miss lock in code - introduce race conditions. 
- Possible to forget/miss unlock making it deadlocked forever. 
- Requires tuning for different sizes of cluster and speed of new TG being created/updated.

We can also partition locks, somehow...

There is also idiomatic go approach - goroutine that manages target groups and takes ownership for create/delete/cleanup. When reconciler pass request over channel to the TG synthesizer and wait response back. TG synth has a select statement that handles new requests and GC cycles.

Whatever approach we take, first step is make TG Synthesizer stateful and re-usable between multiple requests. Right now we instantiate new Synth every Deploy call.
