### ISSUE TITLE
latest version of the controller failing to create default DNS names for HttpRoute CRDs 

### ISSUE THREAD

**Issue by neelaruban** [aws/aws-application-networking-k8s#558]
the current latest version of the controller `v1.01` failing to create default DNS names for the routes . 

errors observed are given below

 

`{"level":"info","ts":"2023-12-04T04:56:59.304Z","logger":"controller.route","caller":"controllers/route_controller.go:152","msg":"reconcile","name":"inventory"}
{"level":"info","ts":"2023-12-04T04:56:59.304Z","logger":"controller.route","caller":"controllers/route_controller.go:265","msg":"Found aws-vpc-lattice for Route for inventory, default"}
{"level":"info","ts":"2023-12-04T04:56:59.304Z","logger":"controller.route","caller":"controllers/route_controller.go:311","msg":"reconcile, adding or updating","name":"inventory"}
{"level":"info","ts":"2023-12-04T04:56:59.304Z","logger":"controller.route","caller":"gateway/model_build_lattice_service.go:125","msg":"No custom-domain-name for route inventory-default"}
{"level":"info","ts":"2023-12-04T04:56:59.385Z","logger":"controller.route","caller":"controllers/route_controller.go:155","msg":"reconcile error","name":"inventory","message":"error during tg synthesis error during target group synthesis, will retry"}
{"level":"info","ts":"2023-12-04T04:57:19.304Z","logger":"controller.route","caller":"controllers/route_controller.go:152","msg":"reconcile","name":"rates"}
{"level":"info","ts":"2023-12-04T04:57:19.305Z","logger":"controller.route","caller":"controllers/route_controller.go:265","msg":"Found aws-vpc-lattice for Route for rates, default"}
{"level":"info","ts":"2023-12-04T04:57:19.305Z","logger":"controller.route","caller":"controllers/route_controller.go:311","msg":"reconcile, adding or updating","name":"rates"}
{"level":"info","ts":"2023-12-04T04:57:19.305Z","logger":"controller.route","caller":"gateway/model_build_lattice_service.go:125","msg":"No custom-domain-name for route rates-default"}
{"level":"info","ts":"2023-12-04T04:57:19.396Z","logger":"controller.route","caller":"controllers/route_controller.go:155","msg":"reconcile error","name":"rates","message":"error during tg synthesis error during target group synthesis, will retry"}
`

**Comment by mikhail-aws** [comment]
can you provide please debug logs and manifest too?
you can enable debug logging with env variable LOG_LEVEL=debug, or with helm using values log.level=debug

**Comment by neelaruban** [comment]
@mikhail-aws  i just found out the v1.0.1 helm chart is buggy too as setting `log.level=debug` does not work 

for you information this is how i am setting up the helm chart values via blueprint-addons 

```hcl
resource "test" "foo" {
enable_aws_gateway_api_controller = true
  aws_gateway_api_controller = {
    repository_username = data.aws_ecrpublic_authorization_token.token.user_name
    repository_password = data.aws_ecrpublic_authorization_token.token.password
    chart_version = "v1.0.0"
    # awsRegion, clusterVpcId, clusterName, awsAccountId are required for case where IMDS is NOT AVAILABLE, e.g Fargate, self-managed clusters with IMDS access blocked
    set = [{
      name  = "clusterVpcId"
      value = module.vpc.vpc_id
    },
    {
      name = "clusterName"
      value = module.eks.cluster_name
    },
    {
      name = "defaultServiceNetwork"
      value = "my-hotel"
    },
    {
      name = "log.level"
      value = "debug"
    }
    ]
  }
```
The actual issue is that the HttpRoute CRD is failing to reconcile to create default lattice generated domains for the manifest given below

```yaml
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: rates
spec:
  parentRefs:
  - name: my-hotel
    sectionName: http
  rules:
  - backendRefs:
    - name: parking
      kind: Service
      port: 80
    matches:
    - path:
        type: PathPrefix
        value: /parking
  - backendRefs:
    - name: review
      kind: Service
      port: 80
    matches:
    - path:
        type: PathPrefix
        value: /review

```
 the controller keeps on looking for the custom domain instead of creating lattice generated default domains 
 
 ```shell
{"level":"info","ts":"2023-12-05T23:44:52.619Z","logger":"controller.route","caller":"gateway/model_build_lattice_service.go:125","msg":"No custom-domain-name for route rates-default"}
{"level":"info","ts":"2023-12-05T23:44:52.651Z","logger":"controller.route","caller":"controllers/route_controller.go:155","msg":"reconcile error","name":"rates","message":"error during tg synthesis error during target group synthesis, will retry"}

 ```

**Comment by neelaruban** [comment]
looks like its due to the fact the current terraform eks blueprint addon module lacks iam permissions for the controller to do its job correctly , i have opened an issue to track it   [here](https://github.com/aws-ia/terraform-aws-eks-blueprints-addons/issues/328)
