### ISSUE TITLE
Support readiness gates for 0-downtime rolling update

### ISSUE THREAD

**Issue by mpuncel** [aws/aws-application-networking-k8s#560]
Currently rolling updates in Kubernetes can cause downtime for a Lattice service. This problem can be solved by using a Kubernetes [pod readiness gate](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-readiness-gate) which indicates that a pod has been successfully synced into Lattice.

This [feature is supported in aws-load-balancer-controller](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.1/deploy/pod_readiness_gate/). It describes the problem well:

> The pod readiness gate is needed under certain circumstances to achieve full zero downtime rolling deployments. Consider the following example:
> * Low number of replicas in a deployment
> *  Start a rolling update of the deployment
> * Rollout of new pods takes less time than it takes the AWS Load Balancer controller to register the new pods and for their health state turn »Healthy« in the target group
> * At some point during this rolling update, the target group might only have registered targets that are in »Initial« or »Draining« state; this results in service outage

> In order to avoid this situation, the AWS Load Balancer controller can set the readiness condition on the pods that constitute your ingress or service backend. The condition status on a pod will be set to True only when the corresponding target in the ALB/NLB target group shows a health state of »Healthy«. This prevents the rolling update of a deployment from terminating old pods until the newly created pods are »Healthy« in the ALB/NLB target group and ready to take traffic.

I believe the Lattice controller would need to be modified to sync pods that are not yet ready (or in [ContainersReady status](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-conditions)) into Lattice target groups. It would also need to inject a pod readiness gate into newly created pods, and then update this pod readiness gate's status once the pod has been synced to Lattice.

**Comment by graehren** [comment]
Hi @mpuncel, we are looking at a few options which should address this issue.
1. Add support for a K8S deployment object “[Min Ready Seconds](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#min-ready-seconds)” with an initial target of 60 seconds. 
2. Leverage Gateway API weighted BackendRef feature to manually rollout an upgrade with no downtime
3. Lattice to provide support for [Argo rollouts-plugin-trafficrouter-gateway API](https://github.com/argoproj-labs/rollouts-plugin-trafficrouter-gatewayapi/)

We will provide more details in January on this testing, but please let us know if you have any other questions or feedback.

**Comment by solmonk** [comment]
About pod readiness gate support - If `readinessGates` field needs to be defined in Pod/Deployment spec instead of being injected by controller, would this work for your use case as well? @mpuncel

**Comment by solmonk** [comment]
Created #596 to track injection webhook independently.

**Comment by zijun726911** [comment]
Done by #605 #606 #607 #608
