### ISSUE TITLE
EKS Gateway API support without VPC Lattice

### ISSUE THREAD

**Issue by vijaymateti** [aws/aws-application-networking-k8s#562]
Is there option to implement AWS managed Gateway API provider for EKS similar to ALB ingress controller without dependency with VPC lattice. There could be many reason why somone may not want to integrate VPC lattice and use something like Istio/Linkerd for service mesh experience.

**Comment by mikhail-aws** [comment]
Currently aws-application-networking-k8s is built for VPC-Lattice. There are many implementations of Gateway API spec. 

You can try Istio Gateway API implementation https://gateway-api.sigs.k8s.io/implementations/#istio
And Istio with EKS https://aws.amazon.com/blogs/opensource/getting-started-istio-eks/

I didnt quite get the question about 

> AWS managed Gateway API provider for EKS similar to ALB ingress controller without dependency with VPC lattice

 ALB ingress controller implements Ingress Spec with provisioning ALB.
aws-application-networking-k8s implements Gateway API Spec with provisioning VPC-Latttice. 

ALB does not depends on Lattice same as Lattice does not depend on ALB. It's a different Specs and different implementations.

**Comment by mikhail-aws** [comment]
Feel free to re-open if you have more questions.

**Comment by geowalrus4gh** [comment]
@mikhail-aws K8s Gateway Spec is originally designed for North-South traffic. Later it introduced East-West too. One naturally expects North-South traffic when someone takes k8s Gateway Spec for implementation. 

The same question is asked in both 'aws lb controller' and 'aws gateway controller'

1. https://github.com/aws/aws-application-networking-k8s/issues/535
2. https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1338
