### ISSUE TITLE
Controller failing to associate lattice service with service network in different account.

### ISSUE THREAD

**Issue by prys** [aws/aws-application-networking-k8s#565]
I have a VPC Lattice Service Network ('my-hotel') defined in AWS Account A. This is RAM-shared to Account B, where I am running my EKS cluster. I can see the Service Network when logged into the console and cli of Account B. I can successfully associate my EKS VPC with the 'my-hotel' service network. 

Following the Quick Start guide, I deploy the 'parking' and 'review' kubernetes deployments and services into my cluster, and then the 'rates' HTTPRoute resource using the rate-route-path.yaml in the example folder. This creates the 'rates-default' lattice service and two target groups - 'k8s-default-review-qmsuilsxyq' and 'k8s-default-parking-koyqfohudh'. These are visible in the console of Account B, but not visible from Account A.

The controller fails to associate the 'rates-default' service with the 'my-hotel' Service Network. With debug logging on, the controller logs: -

`{"level":"debug","ts":"2023-12-08T11:03:40.393Z","logger":"cloud","caller":"aws/cloud.go:65","msg":"response","serviceName":"VPC Lattice","operation":"ListServiceNetworks","params":"{\n\n}"}
{"level":"info","ts":"2023-12-08T11:03:40.394Z","logger":"controller.route","caller":"controllers/route_controller.go:155","msg":"reconcile error","name":"rates","message":"error during service synthesis failed ServiceManager.Upsert rates-default due to Service network my-hotel not found"}`

I am able to manually associate the 'rates-default' service with the 'my-hotel' service network via the console, logged in to Account B.

Have I missed something to allow the controller to create lattice services / target groups _and_ associate with a lattice service in a different aws account?

**Comment by mikhail-aws** [comment]
There is confirmed issue on controller/lattice side with RAM. It might be your case, but I recommend double check on your side.

There was recent change on controller side to use tags for ownership for shared resource like SN. When SN is shared with you through RAM there is no option to allow ListTagsForResource.

`aws vpc-lattice list-tags-for-resource --resource-arn ${shared_sn_arn}`

This call will fail, even if you grant "full" permission in RAM AWSRAMPermissionVpcLatticeServiceNetworkReadWrite
You should see something like this in debug or error logs:

`An error occurred (AccessDeniedException) when calling the ListTagsForResource operation: User: arn:aws:sts::Redacted:assumed-role/Redacted is not authorized to perform: vpc-lattice:ListTagsForResource on resource: arn:aws:vpc-lattice:us-west-2:Redacted:servicenetwork/sn-Redacted`

We are looking into solutions.

**Comment by mikhail-aws** [comment]
it should be fixed now and will be released in v1.0.2 soon

**Comment by mikhail-aws** [comment]
please try new release, closing ticket for now

**Comment by prys** [comment]
Thank you @mikhail-aws . Yes, I can confirm the new release works as desired, and allows the controller to create a service and associate with a service network in a different account.
