### ISSUE TITLE
Support Multi-Arch Builds(ARM64)

### ISSUE THREAD

**Issue by kamirendawkins** [aws/aws-application-networking-k8s#579]
Currently the Gateway API Controller Pods do not appear to support ARM64 Arch, as an AWS consumer using Graviton where possible is a preference so multi-arch support would be greatly appreciated.

Issue based on:
1. Public ECR not specifying supported archs: https://gallery.ecr.aws/aws-application-networking-k8s/aws-gateway-controller
1. Pods launched on ARM based instances resulting in:
  ```bash
  exec /manager: exec format error
  ```

**Comment by mikhail-aws** [comment]
Yes, there is no ARM64 support right now and it would be nice to support. There are few active tasks related to our build and release automation which should help us with new platforms.

**Comment by mikhail-aws** [comment]
We can do few tweaks in our release script, to make it easier run custom builds, so you can build it by yourself for any platform. That should serve short term, until we have proper support for ARM.

@zijun726911 , I see there are values in script that hard-coded for our own build(ECR_PUBLISH_ROLE_ARN), can we make them customizable? like this:

```
IMAGE_TAG=${IMAGE_TAG:-$VERSION}
```

https://github.com/aws/aws-application-networking-k8s/blob/main/scripts/release-controller.sh

**Comment by zijun726911** [comment]
Yes, will try to figure out how to build multi platform in the next release

https://github.com/aws/amazon-vpc-cni-k8s/blob/048a66a55cae2e7e7c9123b5dc6b159c1a4d04f2/Makefile#L173

**Comment by zijun726911** [comment]
Done in the #598
