### ISSUE TITLE
runtime error: failed to deploy the controller pods in amd64 node

### ISSUE THREAD

**Issue by hulu-xu** [aws/aws-application-networking-k8s#586]
## descriptions
When I deploy the gateway-api-controller **v1.0.2** in a Bottlerocket node created by karpenter, the controller pod shows the following error.
```
{"level":"info","ts":"2024-01-15T05:50:08.212Z","logger":"setup","caller":"workspace/main.go:112","msg":"init config","VpcId":"vpc-05780dce19bd43c1e","Region":"ap-southeast-2","AccountId":"184443265312","DefaultServiceNetwork":"gateway-api-vpc-lattice","ClusterName":"eks-alpha-ap-southeast-2-dev","LogLevel":"info"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xbca89b]

goroutine 1 [running]:
github.com/aws/aws-application-networking-k8s/pkg/aws/services.(*defaultLattice).FindServiceNetwork(0xc00067f758?, {0x20d62e8, 0xc00004e020}, {0xc000044078?, 0xc0009bc930?})
	/workspace/pkg/aws/services/vpclattice.go:397 +0x1db
github.com/aws/aws-application-networking-k8s/pkg/deploy/lattice.(*defaultServiceNetworkManager).CreateOrUpdate(0xc000a0d7a0, {0x20d62e8, 0xc00004e020}, 0xc0009b8e10)
	/workspace/pkg/deploy/lattice/service_network_manager.go:163 +0xae
github.com/aws/aws-application-networking-k8s/pkg/controllers.RegisterGatewayController(0xc00012a480, {0x20db2d0?, 0xc00039c070}, {0x20c2788?, 0xc00012dd30}, {0x20e1098, 0xc000396ea0})
	/workspace/pkg/controllers/gateway_controller.go:88 +0x291
main.main()
	/workspace/main.go:167 +0xa52
```
When we rolled back to v1.0.1, the controller pod could run. But it still doesn't work as v1.0.1 lacks some target group polices.

## to reproduce
We use this [manifest]( https://github.com/aws/aws-application-networking-k8s/blob/main/examples/deploy-v1.0.2.yaml) yaml to deploy the controller fllowed by this [doc](https://www.gateway-api-controller.eks.aws.dev/guides/deploy/).

## versions
gateway-api-controller: v1.0.2
Bottlerocket: ami-0a0637f94fab74261 | bottlerocket-aws-k8s-1.28-x86_64-v1.17.0-53f322c2

**Comment by zijun726911** [comment]
Hi @hulu-xu , would like to know did you manually create the `gateway-api-vpc-lattice` vpc lattice service network or not? if you go to the vpc lattice console, can you see the  `gateway-api-vpc-lattice` service network? if Yes, does this service network has this tag `application-networking.k8s.aws/ManagedBy` ? and what the value of this tag?

**Comment by solmonk** [comment]
This seems like a bug of improper error handling introduced by a new code path in v1.0.2, and the trigger is 403 AccessDeniedException on VPC Lattice ListTagsForResource API. One possible cause of hitting this error is using RAM shared service network, but I assume this is not the case.

Fixing IAM permission could be a workaround here. Could you also check if you have sufficient permission, particularly `vpc-lattice:ListTagsForResource`?

**Comment by hulu-xu** [comment]
@zijun726911 yes, we created the vpc lattice manually, and there are no tags on it. 
@solmonk we downgrade the version to v1.0.1, it shows lack permission vpc-lattice:ListTagsForResource and added it, but we didn't test the v1.0.2 again.

**Comment by mikhail-aws** [comment]
@solmonk, yes, missing "else" statement. It suppose to be ErrCodeAccessDeniedException on fetching tags. 
https://github.com/aws/aws-application-networking-k8s/blob/main/pkg/aws/services/vpclattice.go#L396

**Comment by solmonk** [comment]
ManagedBy tag indicates the resource is owned and created by the controller. It contains some information such as cluster name and VPC ID. I think @zijun726911 asked about this to have better understanding on the situation, but since you have created the resource by yourself you may ignore that question.

As long as you have the right permissions I think you will be fine with v1.0.2 as well, but we will still ship a bugfix targeting next release. Thanks!

**Comment by solmonk** [comment]
Closing as v1.0.3 is released, please feel free to reopen if you are seeing other issues.
