### ISSUE TITLE
Support for EKS Pod Identity

### ISSUE THREAD

**Issue by askulkarni2** [aws/aws-application-networking-k8s#593]
Amazon EKS [launched](https://aws.amazon.com/about-aws/whats-new/2023/11/amazon-eks-pod-identity/) to simplify IAM configuration for pods. In order for AWS Gateway API Controller to support this, it will need to use an AWS SDK version that provides the new credential provider logic available >= [v1.47.11](https://github.com/aws/aws-sdk-go/releases/tag/v1.47.11). 

#554 is somewhat related to this as well.

**Comment by solmonk** [comment]
Thanks for reporting this, the sdk version bump has been merged.

I feel like we could also update the docs/deployment instructions with this.

**Comment by zijun726911** [comment]
That's a good call out. In the controller guidance, it uses the old way `eksctl utils associate-iam-oidc-provider` to provide IAM permissions for the controller pod https://github.com/aws/aws-application-networking-k8s/blob/main/docs/guides/deploy.md

Instead, It can change to the newer and easier `eksctl create podidentityassociation`  approach (with eks-pod-identity-agent addon) https://eksctl.io/usage/pod-identity-associations/#introduction

We can update the [deploy.md](https://github.com/aws/aws-application-networking-k8s/blob/main/docs/guides/deploy.md) doc.

**Comment by askulkarni2** [comment]
I am happy to help with the doc if needed, let me know.

**Comment by zijun726911** [comment]
#630 Added in the Pod Identity. Feel free the reopen it if you think that new doc don't work for you  https://github.com/aws/aws-application-networking-k8s/blob/53657780cd55cb53bc462aadd2b82d6088a9b69c/docs/guides/deploy.md?plain=1#L78
