### ISSUE TITLE
[code cleanup] Need to use kube style

### ISSUE THREAD

**Issue by liwenwu-amazon** [aws/aws-application-networking-k8s#61]
for example

use 

kube style for this is typically to use v1alpha1 or mcsv1alpha1` if there's a conflict.   for example,  this [code](https://github.com/aws/aws-application-networking-k8s/blob/main/controllers/serviceexport_controller.go#L33)

**Comment by mikhail-aws** [comment]
an easy pick, rename import statement aliases

**Comment by mikhail-aws** [comment]
write a guidance on imports aliasing for ambiguous names
