### ISSUE TITLE
Put CRD's into a separate Helm Chart

### ISSUE THREAD

**Issue by xonstone** [aws/aws-application-networking-k8s#659]
Currently the Helm Chart only installs/upgraded CRD's on the initial install of the Helm Chart. This is a [well documented issue](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/). 

It would be nice to have a separate Helm Chart for the CRD's as described [here](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#method-2-separate-charts) so we can upgrade these easily along with the controller and avoid issues like https://github.com/aws/aws-application-networking-k8s/issues/658

**Comment by zijun726911** [comment]
By the v1.0.6 controller design, even if the TLSRoute CRD in a separate Helm Chart, but you don't install that separate Helm Chart, the controller won't start successfully. The controller full functionality rely on TLSRoute and some other CRDs installed in the cluster.

What do you think the approach mentioned in this issue: https://github.com/aws/aws-application-networking-k8s/issues/658#issuecomment-2258936391

**Comment by xonstone** [comment]
The separate Helm Chart will help to install the necessary CRD's since if you keep your current Helm Chart (with the CRD's in the crd folder) the CRD's only get installed at the initial `helm install`. 

Once the Helm Chart is installed and you used `helm upgrade` there won't be any additional CRD's installed and may cause issues like https://github.com/aws/aws-application-networking-k8s/issues/658.

This is a [well-documented behaviour](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/) of Helm and they suggest managing the CRD's manually or creating a separate Helm Chart with the CRD's as regular templates not in the CRD folder (which is what I am suggesting to do)

I would opt for the (additional) Helm Chart since you can then automate upgrades and use semver on the Helm Chart to depict breaking changes.

**Comment by graehren** [comment]
@xonstone We appreciate your feedback and have mentioned in the [v1.0.6 release notes](https://github.com/aws/aws-application-networking-k8s/releases/tag/v1.0.6) that customers need to install the Helm chart again or add the new TLSRoute CRD manually. For future EKS Controller enhancements we can add CRD's as an optional upgrade using a separate Helm chart, but we do not plan to move the TLSRoute CRD to make it optional as the code for TLS Passthrough support is coupled with the support for target groups. 

We will update our development guidelines to use an optional Helm chart for upcoming feature enhancements or use Semver (1.x) for feature releases. Does this address your issue?

**Comment by xonstone** [comment]
That seems like a good approach to me! Typically both Helm Charts would have the same version so it's easy to track what version should be installed (like eg [Karpenter](https://karpenter.sh/docs/upgrading/upgrade-guide/#crd-upgrades) does it as well).

In addition I would also look into https://github.com/aws/aws-application-networking-k8s/issues/660. That ticket mentions to error out sooner on startup so mistakes are caught during deployment instead of after it...

**Comment by graehren** [comment]
Thank you,  #660 is a great suggestion for the controller.

**Comment by xonstone** [comment]
Let’s keep this issue open until the separate Helm Chart for CRD’s is implemented.
