### ISSUE TITLE
Audit error handling throughout the codebase

### ISSUE THREAD

**Issue by ellistarn** [aws/aws-application-networking-k8s#66]
Followup from https://github.com/aws/aws-application-networking-k8s/pull/60#discussion_r1039922552.

There are a number of cases where only the NOT_FOUND error case is the only one that is handled. We should go through the code base and make sure that the logical flows handle transient errors, not found errors, and other cases. This can result in resource leakage and code correctness issues.

**Comment by mikhail-aws** [comment]
closing, will track in #316
