### ISSUE TITLE
Release new Helm Chart version

### ISSUE THREAD

**Issue by encron** [aws/aws-application-networking-k8s#668]
Hey there,

Can a new version be released of the Helm Chart so that the recent additions (6b3f146788ba711972650fcc15fd7590b518a107 and 15d0899bb4ccaf4327ab3cac68d058d7d159b39e) can be included?

Thanks

**Comment by erikfuller** [comment]
Hi @encron. Planning to put out a new build once [this PR](https://github.com/aws/aws-application-networking-k8s/pull/672) gets merged in.
