### ISSUE TITLE
How do I make TargetGroup without lattice service?

### ISSUE THREAD

**Issue by wolfdate25** [aws/aws-application-networking-k8s#676]
VPC Lattice can associate target groups (EC2, Lambda, ALB, IP) in a service.
But gateway api controller make own service that not included others.
I think this behavior defeats VPC Lattices pros.
How about make some kind of resource like "K8S Service to Lattice TargetGroup"?
Even if we only have a target group, we can do many things in the console.

**Comment by wolfdate25** [comment]
Like aws-load-balancer-controller's  TargetGroupBinding

**Comment by prys** [comment]
Hello @wolfdate25 . Have a look at the ServiceExport resource - https://www.gateway-api-controller.eks.aws.dev/latest/api-types/service-export/

From the documentation,
"Internally, creating a ServiceExport creates a standalone VPC Lattice [target group](https://docs.aws.amazon.com/vpc-lattice/latest/ug/target-groups.html). Even without ServiceImports, **creating ServiceExports can be useful in case you only need the target groups created; for example, using target groups in the VPC Lattice setup outside Kubernetes."**

As you say, having a Target Group mapped to the k8s service means you can then use that for other lattice services defined by CloudFormation / Terraform or in the console.
