### ISSUE TITLE
Gabadge globally instead of for each resource (e.g. HTTPRoute)

### ISSUE THREAD

**Issue by liwenwu-amazon** [aws/aws-application-networking-k8s#68]
Today, we reconcile every 10 mins for each resource,  e.g. HTTPRoute,  this will not scale

We need to change it to global reconcile at longer interval, e.g. 1 hour, or 2 hours

**Comment by mikhail-aws** [comment]
I dont think having second code path for catching issues that does not work in normal reconciler is a good approach. We should fix issues in reconcilers. Also we did a few bug fixes on resources leaking, so we should be ok(?) for now.
