### ISSUE TITLE
Create serviceexport fails if already present

### ISSUE THREAD

**Issue by sheetaljoshi** [aws/aws-application-networking-k8s#98]
I have not tried this to determine whether serviceexport and serviceimport are idompotent at lattice data plane level (as these are cluster resources). Can the same service simultaneously be imported or exported in two distinct clusters? What is the behavior if so.

**Comment by liwenwu-amazon** [comment]
By running controller with TARGET_GROUP_NAME_LEN_MODE="long",  you should be able to create serviceexport with any name now
